### ISSUE TITLE
test_paired_t_test throws exception

### ISSUE THREAD

**Issue by alexkyllo** [tea-lang-org/tea-lang#6]
```
>>> tea.hypothesize(['Group', 'Anxiety'], ['Group:Real Spider > Picture'])
[...]
Currently considering factorial_ANOVA
Testing assumption: has_one_y.
Property holds.
Testing assumption: is_continuous.
Property holds.
Testing assumption: is_categorical.
Property holds.
Testing assumption: has_two_or_more_categories.
Property holds.
Testing assumption: is_groups_normal.
Property holds.
Testing assumption: has_equal_variance.
Property holds.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/d/projects/tea-lang/tests/integration_tests/test_integration.py", line 364, in <module>
    tea.hypothesize(['Group', 'Anxiety'], ['Group:Real Spider > Picture'])
  File "/mnt/d/projects/tea-lang/tea/api.py", line 133, in hypothesize
    result = evaluate(dataset_obj, relationship, assumptions, study_design)
  File "/mnt/d/projects/tea-lang/tea/evaluate.py", line 396, in evaluate
    test_result = execute_test(dataset, design, combined_data, test)
  File "/mnt/d/projects/tea-lang/tea/evaluate_helper_methods.py", line 747, in execute_test
    stat_result = test_func(dataset, design, combined_data)
  File "/mnt/d/projects/tea-lang/tea/evaluate_helper_methods.py", line 621, in rm_one_way_anova
    res2way = aovrm2way.fit()
  File "/home/jekyllo/envs/tea-lang-mTSGN7iu/lib/python3.7/site-packages/statsmodels/stats/anova.py", line 556, in fit
    raise ValueError('Independent variables are collinear.')
ValueError: Independent variables are collinear.
```

I think Tea should catch this exception and report that the assumptions for this test are unsat.

**Comment by emjun** [comment]
I can't reproduce this error, but in general, Tea should catch these exceptions and take them into consideration when selecting valid tests. Perhaps the better thing would be add collinearity as a constraint that's checked ahead of time. 

This is something I will add to the [V1 Roadmap](https://github.com/emjun/tea-lang/issues/51).

Thanks!!
