### ISSUE TITLE
Tea-lang Olympics example fails

### ISSUE THREAD

**Issue by parsa** [tea-lang-org/tea-lang#86]
I tried to run the [Olympics example](https://github.com/tea-lang-org/tea-lang/blob/master/examples/Olympics/olympics_tea.py) from the Tea-lang repository, and it fails with the following error:

```console
Traceback (most recent call last):
  File "/work/olympics_tea.py", line 50, in <module>
    tea.hypothesize(['Sex', 'Weight'], ['Sex:F < M'])
  File "/usr/local/lib/python3.9/dist-packages/tea/api.py", line 175, in hypothesize
    result = vardata_factory.create_vardata(dataset_obj, relationship, assumptions, study_design)
  File "/usr/local/lib/python3.9/dist-packages/tea/vardata_factory.py", line 56, in create_vardata
    return self.__create_relate_vardata(dataset, expr, assumptions, design)
  File "/usr/local/lib/python3.9/dist-packages/tea/vardata_factory.py", line 398, in __create_relate_vardata
    tests = synthesize_tests(dataset, assumptions, combined_data)
  File "/usr/local/lib/python3.9/dist-packages/tea/z3_solver/solver.py", line 1073, in synthesize_tests
    assumed_props = assume_properties(stat_var_map, assumptions, solver, dataset, combined_data)
  File "/usr/local/lib/python3.9/dist-packages/tea/z3_solver/solver.py", line 1011, in assume_properties
    stat_vars = [stat_var_map[v] for v in var]
  File "/usr/local/lib/python3.9/dist-packages/tea/z3_solver/solver.py", line 1011, in <listcomp>
    stat_vars = [stat_var_map[v] for v in var]
KeyError: 'Sport'
```

Platform:
* OS: Debian Bullseye (Current x86 Python 3.7 Docker image), Linux 5.15.49
* Tea version: 0.4.2 (latest on PyPI)
* Python version: 3.7.16
* Packages installed by `pip install tealang`: attrs-21.4.0 bootstrapped-0.0.2 certifi-2022.12.7 charset-normalizer-2.0.12 cycler-0.11.0 fonttools-4.38.0 idna-3.4 joblib-1.2.0 kiwisolver-1.4.4 matplotlib-3.5.3 mpmath-1.2.1 numpy-1.21.6 packaging-23.0 pandas-1.3.5 parameterized-0.8.1 patsy-0.5.3 pillow-9.4.0 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.7.1 requests-2.27.1 scikit-learn-1.0.2 scipy-1.7.3 six-1.16.0 statsmodels-0.12.2 sympy-1.9 tealang-0.4.2 threadpoolctl-3.1.0 typing-extensions-4.4.0 urllib3-1.26.8 z3-solver-4.8.14.0

To reproduce:

```bash
docker run -it --platform=linux/amd64 python:3.7 bash
```

```bash
pip install tealang
wget https://raw.githubusercontent.com/tea-lang-org/tea-lang/master/examples/Olympics/athlete_events_cleaned_weight.csv
wget https://raw.githubusercontent.com/tea-lang-org/tea-lang/master/examples/Olympics/olympics_tea.py
python olympics_tea.py
```

Output:
```console
$ python olympics_tea.py
Logger was initialized with default configuration.
Use TeaLogger.initialize_logger to change it.

Running under STRICT mode.

This means that user assertions will be checked. Should they fail, Tea will override user assertions.

/usr/local/lib/python3.7/site-packages/scipy/stats/morestats.py:1760: UserWarning: p-value may not be accurate for N > 5000.
  warnings.warn("p-value may not be accurate for N > 5000.")


Results:
--------------
Test: mannwhitney_u
***Test assumptions:
Exactly one explanatory variable: Sport
Exactly one explained variable: Weight
Independent (not paired) observations: Sport
Variable is categorical: Sport
Variable has two categories: Sport
Continuous OR ORDINAL (not nominal) data: Weight

***Test results:
name = Mann Whitney U Test
test_statistic = 46021305.50000
p_value = 1.00000
adjusted_p_value = 1.00000
alpha = 0.05
dof = 18793
Effect size:
A12 = 0.53830
Null hypothesis = There is no difference in medians between Sport = Swimming and Sport = Wrestling on Weight.
Interpretation = t(18793) = 46021305.50000, p = 1.00000. Fail to reject the null hypothesis at alpha = 0.05. There is no difference in medians between Sport = Swimming and Sport = Wrestling on Weight.The effect size is A12 = 0.53830. The effect size is the magnitude of the difference, which gives a holistic view of the results [1].
[1] Sullivan, G. M., & Feinn, R. (2012). Using effect size—or why the P value is not enough. Journal of graduate medical education, 4(3), 279-282.

Test: kruskall_wallis
***Test assumptions:
Independent (not paired) observations: Sport
Exactly one explanatory variable: Sport
Exactly one explained variable: Weight
Continuous (not categorical) data: Weight
Variable is categorical: Sport
Variable has two or more categories: Sport

***Test results:
name = Kruskall Wallis
test_statistic = 72.86194
p_value = 0.00000
adjusted_p_value = 0.00000
alpha = 0.05
dof = 18793
Null hypothesis = There is no difference in medians between Sport = Swimming, Wrestling on Weight.
Interpretation = t(18793) = 72.86194, p = 0.00000. Reject the null hypothesis at alpha = 0.05. There is a difference in medians of Weight for at least one of Sport = Swimming, Wrestling.

Traceback (most recent call last):
  File "olympics_tea.py", line 50, in <module>
    tea.hypothesize(['Sex', 'Weight'], ['Sex:F < M'])
  File "/usr/local/lib/python3.7/site-packages/tea/api.py", line 175, in hypothesize
    result = vardata_factory.create_vardata(dataset_obj, relationship, assumptions, study_design)
  File "/usr/local/lib/python3.7/site-packages/tea/vardata_factory.py", line 56, in create_vardata
    return self.__create_relate_vardata(dataset, expr, assumptions, design)
  File "/usr/local/lib/python3.7/site-packages/tea/vardata_factory.py", line 398, in __create_relate_vardata
    tests = synthesize_tests(dataset, assumptions, combined_data)
  File "/usr/local/lib/python3.7/site-packages/tea/z3_solver/solver.py", line 1073, in synthesize_tests
    assumed_props = assume_properties(stat_var_map, assumptions, solver, dataset, combined_data)
  File "/usr/local/lib/python3.7/site-packages/tea/z3_solver/solver.py", line 1011, in assume_properties
    stat_vars = [stat_var_map[v] for v in var]
  File "/usr/local/lib/python3.7/site-packages/tea/z3_solver/solver.py", line 1011, in <listcomp>
    stat_vars = [stat_var_map[v] for v in var]
KeyError: 'Sport'
```

I'm not familiar with the internals of Tea or have previous experience using it, but I'm happy to help if you can point me in the right direction.

**Comment by parsa** [comment]
It Likely was caused by incompatibility between the current state of the example and the latest release, as it does not reproduce with the latest commit instead of the 0.4.2 release.
